### PR TITLE
Fix table len and extract:variants panic

### LINKED ISSUE #120: `Table::len()` is not computing the right size because of stale entries
This causes issues with `print-size` and the printed summary. I made an ad hoc fix locally for `print-size` which the artifact relies on but we need a more careful fix.

### PR DESCRIPTION
**Pull request by clyben**
This PR fixed #120 and #139 
Fixing #120 by adding a new function num_offsets() in table.rs, referring to the original len() function, and changing all original len() call to num_offsets() calls.
Fixing #139 in lib.rs extract_expr's default case, only call self.extract_variants() when it's a sort, excluding the case when it's a base type.

### CODE REVIEW

File: src/function/table.rs [hunk 1]
```diff
@@ -182,13 +182,18 @@ impl Table {
     }
 
     /// One more than the maximum (potentially) valid offset into the table.
-    pub(crate) fn len(&self) -> usize {
+    pub(crate) fn num_offsets(&self) -> usize {
         self.vals.len()
     }
 
+    /// One more than the actual valid offset (not including stale) into the table.
```
Comment (oflatt) [inline src/function/table.rs:189]: Is this comment right?

Comment (clyben) [reply src/function/table.rs:189]: I think so? The table len not including stale should be the actual valid offset?

**Comment by oflatt** [comment]
Looks good to me
