### PR TITLE
Fix queries with no variables firing without checking query

### LINKED ISSUE #343: A rule testing a function evaluation against a literal always matches
The following program:
```
(function foo () i64 :merge (min old new))

(rule ((= (foo) 5)) ((set (foo) 4)))

(set (foo) 10)

(run 3)

(query-extract (foo))
```
prints `4`, meaning that the rule was matched. This seems unexpected, to me the rule could only match if the condition was `(= (foo) 10)`.

Strangely, replacing `5` in the condition by `(+ 1 4)` now gives the expected behavior (i.e. the rule does not match).

It is as if `5` was treated as a free variable in this case, instead of referring to the literal `5` (this might not make any sense, I have 0 knowledge of egglog's internals).

Am I missing something?

Thanks!

### PR DESCRIPTION
**Pull request by oflatt**
Fixes #343, which demonstrated that queries without variables always match. This PR fixes it by handling the edge case, also adding a `SearchResult` abstraction.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -470,6 +470,17 @@ impl Default for EGraph {
 #[error("Not found: {0}")]
 pub struct NotFoundError(Expr);
 
+/// For each rule, we produce a `SearchResult`
+/// storing data about that rule's matches.
+/// When a rule has no variables, it may still match- in this case
+/// the `matched` field is used.
```
Comment (saulshanabrook) [inline src/lib.rs:476]: Do you mean the `do_match` field?

File: src/lib.rs [hunk 2]
```diff
@@ -936,13 +947,15 @@ impl EGraph {
...
+            let mut all_matches = vec![];
             if rule.banned_until <= iteration {
                 let mut fuel = safe_shl(match_limit, rule.times_banned);
                 let rule_search_start = Instant::now();
+                let mut did_match = false;
                 self.run_query(&rule.query, rule.todo_timestamp, |values| {
+                    did_match = true;
                     assert_eq!(values.len(), rule.query.vars.len());
-                    all_values.extend_from_slice(values);
+                    all_matches.extend_from_slice(values);
```
Comment (saulshanabrook) [inline src/lib.rs:958]: Is `did_match` the same as `all_matches` being non empty?

**Review by saulshanabrook — COMMENTED** [review]
Thanks for fixing this weird bug! Just had a few small questions

File: src/lib.rs (hunk 1 above)
Comment (oflatt) [reply src/lib.rs]: yes, fixed

File: src/lib.rs (hunk 2 above)
Comment (oflatt) [reply src/lib.rs:958]: No- since `all_matches` is a flat vector of matches, when there are no variables it is always empty.

Comment (saulshanabrook) [reply src/lib.rs:958]: Cool, that makes sense!

**Review by saulshanabrook — APPROVED** [review]
